services:
  climate-monitoring-web:
    build: .
    image: climate/frontend:phase2
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      GATEWAY_PUBLIC_URL: "http://179.236.231.32:18080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.climate-web.rule=Host(`${CLIMATE_DOMAIN:-analisissistemas2026proyecto.xyz}`)
      - traefik.http.routers.climate-web.entrypoints=websecure
      - traefik.http.routers.climate-web.tls=true
      - traefik.http.routers.climate-web.tls.certresolver=letsencrypt
      - traefik.http.services.climate-web.loadbalancer.server.port=4200
    read_only: true
    cap_drop: [ALL]
    security_opt: ["no-new-privileges:true"]
